service: hello-world

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}  # Usa 'dev' por defecto si no se especifica
  environment: # Variables disponibles dentro del código de tus funciones Lambda
    ENDPOINT_ROOT: ${env:ENDPOINT_ROOT, 'cupcakeslife'}
    CATEGORY_MODULE: ${env:CATEGORY_MODULE, 'categorias'}

functions:
  hello-world:
    handler: ./src/category/handlers/getUser.hello
    events:
      - http:
          path: hello
          method: GET
  
  getCategoriesNameImageCount: # Funcion Lambda
    handler: ./src/category/handlers/getCategoriesNameImageCount.handler
    events:
      - http: # Endpoint en API Gateway REST
          path: ${self:custom.endpointRoot}/${self:custom.categoryModule}/categorias-imagen-cantidad
          method: get
          cors: true
      - http: # Endpoint en API Gateway REST
          path: ${self:custom.endpointRoot}/${self:custom.categoryModule}/categorias-imagen-cantidad/usuario
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-dotenv-plugin

custom:
  endpointRoot: ${env:ENDPOINT_ROOT, 'cupcakeslife'}    # Variables disponibles en rutas o configuraciones dentro del archivo YAML
  categoryModule: ${env:CATEGORY_MODULE, 'categorias'}  # Por defecto usa 'categorias' si no encuentra el .env
  customDomain:
    domainName: thecupcakelife.com
    basePath: ''                         # No agrega /prod en la ruta
    stage: prod                          # Solo aplica en 'prod'
    createRoute53Record: true            # (opcional) crea el registro DNS
    endpointType: 'regional'             # Puede ser 'edge' o 'regional'
    securityPolicy: tls_1_2