service: hello-world
frameworkVersion: "3"
useDotenv: true

params:
  dev:
    VpcId: vpc-02b24c56982844a6f
    SubnetIdA: subnet-0e533b15b927c27d5
    SubnetIdB: subnet-09747a532ca000dc2

custom:
  stage: ${opt:stage, 'local'}

  endpointRoot: ${env:ENDPOINT_ROOT, 'cupcakeslife'}
  categoryModule: ${env:CATEGORY_MODULE, 'categorias'}
  cupcakeModule: ${env:CUPCAKE_MODULE, 'cupcakes'}
  festivityModule: ${env:FESTIVITY_MODULE, 'festividades'}
  ingredientModule: ${env:INGREDIENT_MODULE, 'ingredientes'}
  packageModule: ${env:PACKAGE_MODULE, 'paquetes'}
  recipeModule: ${env:RECIPE_MODULE, 'recipes'}
  userModule: ${env:USER_MODULE, 'usuarios'}

  db:
    username: ${env:DB_USER, 'postgres'}
    password: ${env:DB_PASSWORD, 'postgres'}
    dbName:    ${env:DB_NAME, 'cupcakes'}

  # basePath por stage
  basePathByStage:
    local: local
    dev: dev
    prod: ""

  # crear registro DNS solo en entornos remotos
  createRecord:
    local: false
    dev: true
    prod: true

  # Dominio personalizado (API Gateway + CloudFront edge)
  customDomain:
    domainName: api.thecupcakelife.com
    basePath: ${self:custom.basePathByStage.${self:custom.stage}}
    stage: ${self:custom.stage}
    endpointType: edge        # Edge requiere REST (events:http)
    apiType: rest
    createRoute53Record: ${self:custom.createRecord.${self:custom.stage}}
    securityPolicy: tls_1_2
    certificateArn: arn:aws:acm:us-east-1:823999505065:certificate/67ca50d3-f7a6-4c45-943d-b58276c70451

  # CORS reusable
  corsCommon:
    origins:
      - https://www.thecupcakelife.com
      - https://thecupcakelife.com
    headers:
      - Content-Type
      - Authorization
    allowCredentials: false
    cacheControl: 'max-age=600'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: ${self:custom.stage}

  vpc:
    securityGroupIds:
      - Ref: MyLambdaSecurityGroup
    subnetIds:
      - ${param:SubnetIdA, 'subnet-00000000000000000'}
      - ${param:SubnetIdB, 'subnet-00000000000000000'}

  environment:
    ENDPOINT_ROOT: ${self:custom.endpointRoot}
    CATEGORY_MODULE: ${self:custom.categoryModule}
    CUPCAKE_MODULE: ${self:custom.cupcakeModule}
    FESTIVITY_MODULE: ${self:custom.festivityModule}
    INGREDIENT_MODULE: ${self:custom.ingredientModule}
    PACKAGE_MODULE: ${self:custom.packageModule}
    RECIPE_MODULE: ${self:custom.recipeModule}
    USER_MODULE: ${self:custom.userModule}
    DB_HOST: ${env:DB_HOST, '127.0.0.1'}
    DB_PORT: ${env:DB_PORT, '5432'}
    DB_USER: ${env:DB_USER, 'postgres'}
    DB_PASSWORD: ${env:DB_PASSWORD, 'postgres'}
    DB_NAME: ${env:DB_NAME, 'cupcakes'}
    PGSSLMODE: ${env:PGSSLMODE, 'require'}

functions: ${file(./functions.yml)}

plugins:
  - serverless-offline
  - serverless-domain-manager

package:
  patterns:
    - package.json

resources:
  Conditions:
    IsDev:
      Fn::Equals:
        - ${self:custom.stage}
        - dev

  Resources:
    MyDbSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Condition: IsDev
      Properties:
        DBSubnetGroupDescription: "Subnet group RDS (dev)"
        SubnetIds:
          - ${param:SubnetIdA, 'subnet-00000000000000000'}
          - ${param:SubnetIdB, 'subnet-00000000000000000'}

    MyLambdaSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Condition: IsDev
      Properties:
        GroupDescription: "Lambda SG (dev)"
        VpcId: ${param:VpcId, 'vpc-00000000000000000'}

    MySecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Condition: IsDev
      Properties:
        GroupDescription: "Allow access to Postgres DB (dev)"
        VpcId: ${param:VpcId, 'vpc-00000000000000000'}
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 5432
            ToPort: 5432
            CidrIp: "38.43.130.101/32"
          - IpProtocol: tcp
            FromPort: 5432
            ToPort: 5432
            SourceSecurityGroupId:
              Ref: MyLambdaSecurityGroup

    MyPostgresDB:
      Type: AWS::RDS::DBInstance
      Condition: IsDev
      Properties:
        DBInstanceClass: db.t3.micro
        Engine: postgres
        EngineVersion: "17.6"
        DBInstanceIdentifier: ${self:service}-${self:custom.stage}-db
        MasterUsername: ${self:custom.db.username}
        MasterUserPassword: ${self:custom.db.password}
        DBName: ${self:custom.db.dbName}
        AllocatedStorage: 20
        StorageType: gp2
        PubliclyAccessible: true
        MultiAZ: false
        AutoMinorVersionUpgrade: true
        BackupRetentionPeriod: 1
        DBSubnetGroupName:
          Ref: MyDbSubnetGroup
        VPCSecurityGroups:
          - Ref: MySecurityGroup

  Outputs:
    RdsEndpoint:
      Condition: IsDev
      Description: "RDS endpoint (host)"
      Value:
        Fn::GetAtt: [ MyPostgresDB, Endpoint.Address ]
