service: hello-world

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello-world:
    handler: ./src/category/handlers/getUser.hello
    events:
      - http:
          path: hello
          method: GET
  
  # getCategoriesNameImageCount:
  #   handler: src/category/handlers/getCategoriesNameImageCount.handler
  #   events:
  #     - http:
  #         path: categorias-imagen-cantidad
  #         method: get
  #         cors: true

plugins:
  - serverless-offline
