### Variables de prueba ###
@rootUrlLocal = http://localhost:3000
@rootUrlDev = https://api.thecupcakelife.com
@stageLocal = local
@stageDev = dev
@appName = cupcakeslife
@festivityModule = festividades

### Comprobar variables
### Local
GET https://postman-echo.com/get?rootUrl={{rootUrlLocal}}
### Desarrollo
GET https://postman-echo.com/get?rootUrl={{rootUrlDev}}
### Variables de prueba ###

### GET Nombre, imagen principal y cantidad de los Registros de la tabla cupcake_categorias.
### Local
GET {{rootUrlLocal}}/{{stageLocal}}/{{appName}}/{{festivityModule}}/festividades-imagen-cantidad
### Desarrollo
GET {{rootUrlDev}}/{{stageDev}}/{{appName}}/{{festivityModule}}/festividades-imagen-cantidad

### GET Nombre, imagen principal y cantidad de los Registros de la tabla cupcake_categorias que este disponibles para un usuario por id.
### Local
GET {{rootUrlLocal}}/{{stageLocal}}/{{appName}}/{{festivityModule}}/festividades-imagen-cantidad/usuario?email=asdrubaloviedo@gmail.com
### Desarrollo
GET {{rootUrlDev}}/{{stageDev}}/{{appName}}/{{festivityModule}}/festividades-imagen-cantidad/usuario?email=asdrubaloviedo@gmail.com

