### Variables de prueba ###
@rootUrlLocal = http://localhost:3000
@rootUrlDev = https://api.thecupcakelife.com
@stageLocal = local
@stageDev = dev
@appName = cupcakeslife
@recipeModule = recipes

### Comprobar variables
### Local
GET https://postman-echo.com/get?rootUrl={{rootUrlLocal}}
### Desarrollo
GET https://postman-echo.com/get?rootUrl={{rootUrlDev}}
### Variables de prueba ###

### GET Receta de cupcake por id.
### Local
GET {{rootUrlLocal}}/{{stageLocal}}/{{appName}}/{{recipeModule}}/receta?id=1
### Desarrollo
GET {{rootUrlDev}}/{{stageDev}}/{{appName}}/{{recipeModule}}/receta?id=1
